name: Java CI with Maven

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (branch develop)
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: List files (debug)
        run: ls -R

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.412+8'
          distribution: 'temurin'
          cache: maven

      - name: Build & Test with Coverage
        run: mvn clean verify -f roman-number/pom.xml

      - name: Report to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: mvn coveralls:report -f roman-number/pom.xml
