name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Verify structure
      run: ls Assignment2/roman-number/pom.xml

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and test
      working-directory: Assignment2/roman-number
      run: mvn -B verify jacoco:report

    - name: Coveralls
      working-directory: Assignment2/roman-number
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: mvn coveralls:report
