name: Java CI with Maven

on:
  push:
    branches:
      - develop  
  pull_request:
    branches:
      - develop  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      # Set up JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.412+8'
          distribution: 'temurin'
          cache: 'maven'

      # Entra nella cartella 'roman-number' (dove si trova il pom.xml)
      - name: Go to project directory
        run: cd roman-number

      # Build con Maven
      - name: Build with Maven
        run: mvn -B package --file roman-number/pom.xml

      # Esegui i test con JaCoCo
      - name: Test with JaCoCo
        run: mvn test jacoco:report --file roman-number/pom.xml

      # Report su Coveralls
      - name: Report to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: mvn coveralls:report --file roman-number/pom.xml
