name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.412+8'
          distribution: 'temurin'
          cache: maven
      - name: Build, Test, Checkstyle
        run: mvn install checkstyle:check
      - name: Generate JaCoCo Report
        run: mvn jacoco:report
      - name: Report to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
        run: mvn coveralls:report
