name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.412+8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      working-directory: roman-number
      run: mvn -B package

    - name: Test with JaCoCo
      working-directory: roman-number
      run: mvn test jacoco:report

    - name: Report to Coveralls
      working-directory: roman-number
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: mvn coveralls:report
