name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout esplicito con path personalizzato
    - uses: actions/checkout@v4
      with:
        path: 'main'  # Cartella custom per evitare conflitti

    # 2. DEBUG: Mostra struttura cartelle (puoi rimuoverlo dopo)
    - name: Debug structure
      run: |
        echo "Contenuto repository:"
        ls -R
        echo "Verifica pom.xml:"
        ls develop/roman-number/pom.xml || { echo "##[error] POM NON TROVATO"; exit 1; }

    # 3. Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # 4. Build e test
    - name: Build with Maven
      working-directory: develop/roman-number
      run: mvn -B clean package

    # 5. Test e coverage
    - name: Run tests
      working-directory: develop/roman-number
      run: mvn test jacoco:report

    # 6. Coveralls report (opzionale)
    - name: Coveralls
      if: success()
      working-directory: develop/Assignment2/roman-number
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: mvn coveralls:report
